import express, { RequestHandler } from "express";
import http from "http";
import dotenv from "dotenv";
import cors from "cors";
import { authRouter } from "./router";
import { connectToDb } from "./db_connection";
import { connectToRedis } from "./redis_connection";
import cookieParser from "cookie-parser";
dotenv.config();
const app = express();
// app.use("/api/");
app.use(express.json());
app.use(cookieParser());
app.options("*", cors() as RequestHandler);
app.use(cors());
app.use("/api/auth", authRouter);
const server = http.createServer(app);
const PORT = process.env.PORT || 4000;
connectToDb();
connectToRedis();
server.listen(PORT, () => console.log("Server is running on port:", PORT));
