version: "3"
services:
  api:
    build: .
    image: link_sea_api_img
    ports:
      - "4999:4999"
    container_name: link_sea_api_cunt
    volumes:
      - "./:/app"
    networks:
      - custom_network
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongovol:/data/db
    networks:
      - custom_network
    container_name: link_sea_db

volumes:
  mongovol:
networks:
  custom_network:
